### ISSUE TITLE
Intake/aero parts cause loading screen freeze

### ISSUE THREAD

**Issue by JesusTheBird** [KerboNerd/KNI-HP-CYREX#1]
both parts in aero subfolder cause loading screen(post MM patching) to freeze. once removed, game loads up just fine

**Comment by KerboNerd** [comment]
What version of MM are you running?

**Comment by KerboNerd** [comment]
The issue with MM should be fixed by now. Potential cause was found in the custom resources. They're now reconfigured so i'll close the issue for now. If the error still persists, please open another issue so i knew that the errors still there.
