### ISSUE TITLE
consider creating ksp forum page

### ISSUE THREAD

**Issue by JesusTheBird** [KerboNerd/KNI-HP-CYREX#2]
to discuss improvements or changes. easier for non git users to bug report

ill go first. 
stock a like texturing variants. I find the current textures too dark/black.
optional MM patch for other fuel options(B9PS or MFT?)
optional MM patch for other propulsion options(LFO,Kethane,Liquid Hydrogen?)

Cheers!

**Comment by KerboNerd** [comment]
Noted! Although the main theme for CYREX is matte black, some texturing details will be added.

B9PS is already implemented for some stock skwod tanks!

**Comment by KerboNerd** [comment]
CYREX forum topic now active!
https://forum.kerbalspaceprogram.com/index.php?/topic/184136-17x-hyper-propulsion-sci-fi-parts-pack/
